### ISSUE TITLE
RuntimeError: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by acn-reginald-casela** [SYSTRAN/faster-whisper#790]
Hi, all! I'm trying to deploy an app that uses faster-whisper on google kubernetes engine and I encountered this runtime error when I tried to use "cuda" as the device type.

This is my current docker image file:

```
# Alternatively, use a base image with CUDA and cuDNN support
FROM nvidia/cuda:11.7.1-cudnn8-runtime-ubuntu20.04

# Install necessary dependencies
RUN apt-get update && apt-get install -y python3-pip

# Set the working directory
WORKDIR /app

# Copy the app code and requirements filed
COPY . /app

# Install dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

# Install whisper-ctranslate2
RUN pip install -U whisper-ctranslate2

# Preload model so that startup time isn't too slow
RUN python3 -c 'from faster_whisper import WhisperModel;WhisperModel("large-v2", device="cpu")'
```

and this is the yaml file for deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fasterwhisper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fasterwhisper
  template:
    metadata:
      labels:
        app: fasterwhisper
    spec:
      containers:
      - name: 
        image: 
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "4"
            ephemeral-storage: 1Gi
            memory: 24Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: "4"
            ephemeral-storage: 1Gi
            memory: 24Gi
            nvidia.com/gpu: "1"
      nodeSelector:
        # ask for a GPU node with a Tesla T4 on it
        cloud.google.com/gke-accelerator: nvidia-tesla-t4
        cloud.google.com/gke-accelerator-count: "1"
```

I'm wondering what changes should I do to prevent this error from occuring
